name: test-k3d-action
run-name: ${{ github.actor }} is testing private fork of k3d-action
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  run-k3d-action-private-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: p-se/rancher-sandbox-k3d-action@main
        name: test k3d-action fork
        with:
          cluster-name: test-cluster
          k3d-version: v5.4.6

      - run: k3d --version
